[package]
name = "lilv"
version = "0.1.0"
authors = ["Adrien Prokopowicz <adrien.prokopowicz@gmail.com>"]

[dependencies]
lilv-sys = { path = "./lilv-sys" }
failure = "0.1.2"
lv2 = { path = "../lv2" }

[dev-dependencies]
dlopen = "0.1.5"
regex = "1.0.5"
tempfile = "3.0.4"
rand = "0.6.0-pre.1"

