[package]
name = "lilv-sys"
version = "0.1.0"
authors = ["Adrien Prokopowicz <adrien.prokopowicz@gmail.com>"]

[dependencies]


[build-dependencies]
#bindgen = "0.40.0"
bindgen = "0.32.3"
pkg-config = "0.3.14"
