[package]
name = "playone"
version = "0.1.0"
authors = ["gndl <gndl@users.noreply.github.com>"]
edition = "2018"

[dependencies]
failure = "0.1.8"
granode = { path = "../talker" }
session = { path = "../session" }
#ffmpeg = "0.1.1"
#portaudio = "0.7.0"
