[package]
name = "gramotocaml"
version = "0.1.0"
authors = ["gndl"]

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
ocaml = {git = "https://github.com/zshipko/ocaml-rs"}
gramotor = { path = "../gramotor" }
