if is_devel
    icon_256x256_name = '@0@.256x256.png'.format(base_id)
    icon_128x128_name = '@0@.128x128.png'.format(base_id)
    icon_64x64_name = '@0@.64x64.png'.format(base_id)
    icon_32x32_name = '@0@.32x32.png'.format(base_id)
    icon_16x16_name = '@0@.16x16.png'.format(base_id)
else
    icon_256x256_name = '@0@.256x256.png'.format(base_id)
    icon_128x128_name = '@0@.128x128.png'.format(base_id)
    icon_64x64_name = '@0@.64x64.png'.format(base_id)
    icon_32x32_name = '@0@.32x32.png'.format(base_id)
    icon_16x16_name = '@0@.16x16.png'.format(base_id)
endif

install_data(
    icon_256x256_name,
    install_dir: datadir / 'icons' / 'hicolor' / '256x256' / 'apps',
    rename: '@0@.png'.format(application_id),
)

install_data(
    icon_128x128_name,
    install_dir: datadir / 'icons' / 'hicolor' / '128x128' / 'apps',
    rename: '@0@.png'.format(application_id),
)

install_data(
    icon_64x64_name,
    install_dir: datadir / 'icons' / 'hicolor' / '64x64' / 'apps',
    rename: '@0@.png'.format(application_id),
)

install_data(
    icon_32x32_name,
    install_dir: datadir / 'icons' / 'hicolor' / '32x32' / 'apps',
    rename: '@0@.png'.format(application_id),
)

install_data(
    icon_16x16_name,
    install_dir: datadir / 'icons' / 'hicolor' / '16x16' / 'apps',
    rename: '@0@.png'.format(application_id),
)
