extern crate cpal;
extern crate failure;
extern crate granode;
extern crate lilv;
extern crate lv2;

pub mod audio_data;
pub mod event_bus;
pub mod factory;
pub mod gramotor;
pub mod mixer;
pub mod output;
pub mod playback;
pub mod player;
pub mod plugins_manager;
pub mod session;
pub mod state;
pub mod talkers;
pub mod track;

// use crate::event_bus::EventBus;
// use crate::factory::Factory;
// use crate::mixer::Mixer;
// use crate::output::Output;
// use crate::playback::Playback;
// use crate::player::Player;
// use crate::session::{RSession, Session};
// use crate::talkers::second_degree_frequency_progression;
// use crate::talkers::second_degree_frequency_progression::SecondDegreeFrequencyProgression;
// use crate::talkers::sinusoidal;
// use crate::talkers::sinusoidal::Sinusoidal;
// use crate::track::Track;
